
- name: Initialization Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
    - import_role:
        name: checkpoint
      tags:
      - always 

- hosts: localhost
  tasks:
    - debug: var=control_plane_upgrade_yaml
      tags:
      - always
    - name: Set Control Plane 'In Progress'
      run_once: true
      set_stats:
        data:
          upgrade_phase_control_plane:
            title: "Upgrade - Control Plane"
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
      tags:
        - control_plane
    
- name: Upgrade Control plane
  import_playbook: "{{control_plane_upgrade_yaml}}"
  tags: [control_plane]
  
          
- hosts: localhost
  tasks:
    - name: Set Upgrade Control Plane 'Complete'
      run_once: true
      set_stats:
        data:
          upgrade_phase_control_plane:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
      tags:
        - control_plane

- hosts: localhost
  tasks:
    - name: Set Infra Nodes 'In Progress'
      run_once: true
      set_stats:
        data:
          upgrade_phase_infra_node:
            title: "Upgrade - Infra Nodes"
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
      tags:
        - infra

- name: Upgrade Infra Nodes
  include: "{{node_upgrade_yaml}} openshift_upgrade_nodes_serial={{openshift_upgrade_infra_nodes_serial}} openshift_upgrade_nodes_label={{openshift_upgrade_infra_nodes_label}}"
  tags:
    - infra
          
- hosts: localhost
  tasks:
    - name: Set Upgrade Infra Nodes 'Complete'
      run_once: true
      set_stats:
        data:
          upgrade_phase_infra_node:
            status: "Complete"
      tags:
        - infra
   
- hosts: localhost
  tasks:
    - name: Set App Nodes 'In Progress'
      run_once: true
      set_stats:
        data:
          upgrade_phase_app_node:
            title: "Upgrade - App Nodes"
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
      tags:
        - app 
   
- name: Upgrade App Nodes
  include: "{{node_upgrade_yaml}} openshift_upgrade_nodes_serial={{openshift_upgrade_app_nodes_serial}} openshift_upgrade_nodes_label={{openshift_upgrade_app_nodes_label}}"
  tags:
    - app 
          
- hosts: localhost
  tasks:
    - name: Set Upgrade App Nodes 'Complete'
      run_once: true
      set_stats:
        data:
          upgrade_phase_app_node:
            status: "Complete"
      tags:
        - app 

- hosts: localhost
  tasks:
    - name: Set EFK Logging Stack 'In Progress'
      run_once: true
      set_stats:
        data:
          upgrade_phase_efk:
            title: "Upgrade - EFK Logging Stack"
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
      tags:
        - efk 
   
- name: Upgrade EFK Logging stack
  import_playbook: "{{efk_yaml}} openshift_logging_install_logging=true openshift_logging_image_version={{efk_image_version}}"
  tags: [efk]
          
- hosts: localhost
  tasks:
    - name: Set Upgrade EFK Logging Stack 'Complete'
      run_once: true
      set_stats:
        data:
          upgrade_phase_efk:
            status: "Complete"
      tags:
        - efk

- hosts: localhost
  tasks:
    - name: Set Metrics 'In Progress'
      run_once: true
      set_stats:
        data:
          upgrade_phase_metrics:
            title: "Upgrade - Metrics"
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
      tags:
        - metrics
   
- name: Upgrade Metrics
  include: "{{metrics_yaml}} openshift_metrics_install_metrics=true openshift_metrics_image_version={{metrics_image_version}}"
  tags:
    - metrics
          
- hosts: localhost
  tasks:
    - name: Set Upgrade Metrics 'Complete'
      run_once: true
      set_stats:
        data:
          upgrade_phase_metrics:
            status: "Complete"
      tags:
        - metrics


- hosts: localhost
  tasks:
    - name: Set Service Catalog 'In Progress'
      run_once: true
      set_stats:
        data:
          upgrade_phase_service_catalog:
            title: "Upgrade - Service Catalog"
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
      tags:
        - catalog

- name: Upgrade Service Catalog
  include: "{{service_catalog_yaml}} openshift_enable_service_catalog=true ansible_service_broker_install=true template_service_broker_install=true"
  tags:
    - catalog

- hosts: localhost
  tasks:
    - name: Set Upgrade Service Catalog 'Complete'
      run_once: true
      set_stats:
        data:
          upgrade_phase_service_catalog:
            status: "Complete"
      tags:
        - catalog


