apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nfs-provisioner-pv"
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  nfs:
    path: /exports-nfs
    server: dhcp182-21.gsslab.rdu2.redhat.com
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: nfs-provisioner-pvc
    namespace: nfs-provisioner
