ocp_version: 3.10

# Upgrade
control_plane_upgrade_yaml: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade_control_plane.yml
node_upgrade_yaml: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_10/upgrade_nodes.yml 
efk_yaml: /usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.yml
metrics_yaml: /usr/share/ansible/openshift-ansible/playbooks/openshift-metrics/config.yml

## Upgrade - Metrics
#openshift_metrics_image_version=<tag> 
#openshift_metrics_hawkular_hostname=<fqdn> 
#openshift_metrics_cassandra_storage_type=(emptydir|pv|dynamic) 
###############################################################
metrics_image_version: v3.10
#metrics_hawkular_hostname:

## Upgrade - EFK
#openshift_logging_image_version == efk_image_version
efk_image_version: v3.10

## Upgrade - Node
openshift_upgrade_master_nodes_serial: "50%" 
openshift_upgrade_infra_nodes_serial: "3" 
#openshift_upgrade_app_nodes_serial: "20%" 
openshift_upgrade_app_nodes_serial: "2" 
openshift_upgrade_infra_nodes_label: "region=infra"
openshift_upgrade_app_nodes_label: "region=app"

## Node Upgrade Common variables
openshift_upgrade_nodes_max_fail_percentager: 20 
openshift_upgrade_nodes_drain_timeout: 600
