
- name: Common preresuities
  import_tasks: common.yml
  delegate_to: localhost
  run_once: yes
  become: true
  become_user: root
  
- name: Update atomic-openshift-utils/atomic-openshift-clients
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - atomic-openshift-utils
  - atomic-openshift-clients
  delegate_to: localhost
  run_once: yes
  become: true
  become_user: root
  
