- name: Refresh subscription
  shell: "subscription-manager refresh"
  become: true
  become_user: root

# Too slow
#- name: Enable/Disable repositories for minor upgrade
#  - rhsm_repository:
#      name: "{{ item }}"
#      state: disabled
#    with_items: 
#    - "{{ disable_repoistories }}"
#  
#  - rhsm_repository:
#      name: "{{ item }}"
#      state: enabled
#    with_items: 
#    - "{{ enable_repoistories }}"
#  become: true
#  become_user: root

#- name: Change repos
#  set_fact:
#    disable_repos: "--disable=rhel-7-server-ose-3.7-rpms"
#    enable_repos: "--enable=rhel-7-server-ose-3.9-rpms --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-ansible-2.4-rpms --enable=rhel-7-fast-datapath-rpms"
#  when: "ocp_version == 3.9"

- name: Enable/Disable repositories 
  shell: "{{ item }}"
  with_items:
  - "subscription-manager repos {{ disable_repos }} {{ enable_repos }}"
  - "yum clean all"
  - "yum repolist"
  become: true
  become_user: root

- name: Update atomic-openshift-utils/atomic-openshift-clients
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - atomic-openshift-utils
  - atomic-openshift-clients
  delegate_to: localhost
  run_once: yes
  become: true
  become_user: root

