- name: Refresh subscription
  shell: "subscription-manager refresh"
  become: true
  become_user: root

# Too slow
#- name: Enable/Disable repositories for minor upgrade
#  - rhsm_repository:
#      name: "{{ item }}"
#      state: disabled
#    with_items: 
#    - "{{ disable_repoistories }}"
#  
#  - rhsm_repository:
#      name: "{{ item }}"
#      state: enabled
#    with_items: 
#    - "{{ enable_repoistories }}"
#  become: true
#  become_user: root

- name: Enable/Disable repositories 
  shell: "{{ item }}"
  with_items:
  - "subscription-manager repos {{ disable_repos }} {{ enable_repos }}"
  - "yum clean all"
  - "yum repolist"
  become: true
  become_user: root

